### ISSUE TITLE
Migrating off clerk-sdk-node to clerk express

### ISSUE THREAD

**Issue by videate-josh** [wobsoriano/elysia-clerk#23]
Just a heads up I saw this recently:
https://clerk.com/changelog/2024-10-08-express-sdk

Upgrade Guide:
https://clerk.com/docs/upgrade-guides/node-to-express

I figured it would be good to bring to your attention.

**Comment by wobsoriano** [comment]
Hu @videate-josh! The SDK that's getting deprecated is `@clerk/clerk-sdk-node` and `elysia-clerk` already uses `@clerk/backend`. The difference between these SDKs are:

1. `@clerk/backend` - For any Node.js or Edge runtimes
2. `@clerk/express` - Contains Clerk middleware for express, uses `@clerk/backend` under the hood

Thank you!
