### ISSUE TITLE
Typescript: How to correctly type `auth`

### ISSUE THREAD

**Issue by GautierT** [wobsoriano/elysia-clerk#4]
Hey.

Thanks for this plugin. I created a isSignIn function that i use in beforeHandler. 
How to correctly type it to avoid this error ?

Thanks.

<img width="685" alt="image" src="https://github.com/wobsoriano/elysia-clerk/assets/6089653/fc3e5c4f-87af-474f-9f27-65c7eab7367a">

**Comment by wobsoriano** [comment]
It's a known problem for Elysia plugins when you use them on child Elysia apps.

See https://github.com/elysiajs/elysia/issues/566

**Comment by wobsoriano** [comment]
https://elysiajs.com/essential/scope#plugin
