### ISSUE TITLE
Support for Elysiajs 1.0

### ISSUE THREAD

**Issue by jonnitg** [wobsoriano/elysia-clerk#5]
Are we planning to release a version for the Elysiajs 1.0?

With the [breaking changes](https://elysiajs.com/blog/elysia-10#hook-type-breaking-change) on the hookType "global" and "local" this package might need some updates

**Comment by wobsoriano** [comment]
Yes! Pretty busy at work rn but I'll defo try on the weekend :)

**Comment by jonnitg** [comment]
Please let me know if you need any help

**Comment by wobsoriano** [comment]
I haven’t checked the updates tbh but I’m open to reviewing PRs

**Comment by wobsoriano** [comment]
Released 0.4.0! Thanks y'all!
