### ISSUE TITLE
Elysia 1.2.2 breaks types with elysia-clerk 0.8.8

### ISSUE THREAD

**Issue by mphill** [wobsoriano/elysia-clerk#55]
Once you add `.use(clerkPlugin()) `to a route, everything becomes `any` types for the body, response, and even when using eden.

**Comment by Sly777** [comment]
same on 1.2.4 as well. It looks like there are some breaking changes but as far as I checked the plugin code, I couldn't see any issue tbh. @wobsoriano

**Comment by wobsoriano** [comment]
I'm on Vacation right now but I'll check asap

**Comment by tkoehlerlg** [comment]
Hey @wobsoriano, enjoy your vacation! I looked into the changes made in [elysia-swagge - 1.2.0](https://github.com/elysiajs/elysia-swagger/releases/tag/1.2.0) and it seems that you simply have to update the version. Add a pull request (here)[https://github.com/wobsoriano/elysia-clerk/pull/56]. I've run the tests and they passed. Feel free to look over this again, but it seems that this fixes the problem.

**Comment by wobsoriano** [comment]
Thank you everyone for the help!
